# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21e2325e9bf40a0403401e8180ad5c89e0a99f9886e76b4663627df14734d52c1d0d6e98e876ff8620ffa7eacc7f1a802cb77af042d0e710f38e229e5d11dbbb

test:
  secret_key_base: 3478ed1718aa10b6d3fa99865d45606f92d36422d497cd948c5480f3469906ab536431ca72ddcaf3860deee77c667bf3a99aeb6ac15b3a85aead1b482af576d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
